#
# https://quarto.org/docs/publishing/github-pages.html#publish-action
#
on:
  workflow_dispatch:
  #push:
  #  branches: main

name: Publish guidance

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
            
      - name: Enable stats
        run: |
            # change the line var enabled=false to true.
            sed -i 's/var enabled=false;/var enabled=true;/g' js.html     
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Checkout updated gh-pages
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
